# Generated by Django 5.2.12 on 2026-04-29 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Travel', to='passengers.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='Passengers',
        ),
    ]
