# Generated by Django 5.2.13 on 2026-05-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_passenger_travel_delete_passengers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
